- hosts: terraform-ansible
  tasks:
  - name: Instalando Python3 e VirtualEnv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Instalando depencias com pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/django/venv
      name:
        - django
        - djangorestframework
    

    